### ISSUE TITLE
Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by camille-rodriguez** [tvansteenburgh/greenhouse#2]
Hello there, 

I run the program and I get this everytime :
$ ./post-job.py 1458920 americas
Traceback (most recent call last):
  File "./post-job.py", line 264, in <module>
    main()
  File "./post-job.py", line 190, in main
    existing_locations += [result.text.strip('()') for result in results]
  File "./post-job.py", line 190, in <listcomp>
    existing_locations += [result.text.strip('()') for result in results]
  File "/home/crodriguez/Projects/Recruitment/greenhouse/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/crodriguez/Projects/Recruitment/greenhouse/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/crodriguez/Projects/Recruitment/greenhouse/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/crodriguez/Projects/Recruitment/greenhouse/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.77)

Not sure what is the problem, or if it does refresh the job posts or not before failing on this.

**Comment by tvansteenburgh** [comment]
Hi @camille-rodriguez, thanks for the report.

What page is the browser on when the script crashes? Can you post a screenshot? Do you have the correct [ChromeDriver](https://chromedriver.chromium.org/downloads) installed for your browser version? Have you defined SSO_EMAIL and SSO_PASSWORD or are you entering them manually?

If it would be easier I'm happy to get on a call so I can observe what's happening.

(Not related, but make sure you pass `--region americas`, not just `americas`)
